AllCops:
  DisplayCopNames: true

Metrics/MethodLength:
  Max: 150
Metrics/ClassLength:
  Max: 150
Metrics/AbcSize:
  Max: 200
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/IndentationWidth:
  Enabled: false
Style/ElseAlignment:
  Enabled: false
Lint/EndAlignment:
  Enabled: false
