AllCops:
  DisplayCopNames: true

Metrics/MethodLength:
  Max: 150
Metrics/ClassLength:
  Max: 300
Metrics/AbcSize:
  Max: 200
Metrics/PerceivedComplexity:
  Max: 10

Style/MultilineMethodCallIndentation:
  Enabled: false
Style/IndentationWidth:
  Enabled: false
Style/ElseAlignment:
  Enabled: false
Lint/EndAlignment:
  Enabled: false
