language: ruby
rvm:
  - 2.2.2
cache: bundler
branches:
  only:
    - master
install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get remove -y git
  - travis_retry sudo add-apt-repository "deb http://ppa.launchpad.net/svn/ppa/ubuntu precise main"
  - travis_retry sudo add-apt-repository -y ppa:git-core/ppa
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y git
  - travis_retry sudo apt-get install -y gnuplot
  - travis_retry bundle install
  - git --version
script:
  - rake

